export const API_ENDPOINTS = {
  LOGIN: "/api/login",
  REGISTER: "/api/register",
  USER_PREFERENCES: "/api/user/preferences",
  GET_ALL_CAFES: "/api/data",
  GET_SEARCH_CAFE: "/api/search/",
  GET_REVIEWS: "/api/reviews/",
  GET_USER_BY_ID: "/api/users/",
  GET_DETAIL_CAFE: "/api/cafe/",
  GET_VISITED_CAFES: "/api/visited/",
  VISITED_CAFES: "/api/user/visited",
  GET_MENU_BY_ID: "/api/menu/",
  ADD_FAVORITE_MENU: "/api/user/favorite_menu",
  ADD_FEEDBACK: "/api/feedback",
};
